import React from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
declare global {
  interface Window {
    mail2telegram: {
      invoke: <T = unknown>(command: string, args?: unknown) => Promise<T>;
    };
  }
}

const invoke = <T = unknown>(command: string, args?: unknown) =>
  window.mail2telegram.invoke<T>(command, args);


type Post={id:string;title:string;content:string;source?:string;status:string;created_at?:string};
type Email={id:string;sender?:string;subject?:string;received_at?:string;status:string};

type Config={gmail:boolean;openai:boolean;telegram:boolean};

function App(){
 const [page,setPage]=React.useState('dashboard'); const [status,setStatus]=React.useState('Запуск…');
 const [posts,setPosts]=React.useState<Post[]>([]); const [emails,setEmails]=React.useState<Email[]>([]); const [config,setConfig]=React.useState<Config>({gmail:false,openai:false,telegram:false});
 const [busy,setBusy]=React.useState(false); const [notice,setNotice]=React.useState('');
 const refresh=async()=>{try{setPosts(await invoke<Post[]>('list_posts'));setEmails(await invoke<Email[]>('list_emails'));setConfig(await invoke<Config>('get_config_state'));setStatus('Мониторинг активен')}catch(e){setStatus(String(e))}};
 React.useEffect(()=>{invoke<string>('app_status').then(setStatus).catch(e=>setStatus(String(e)));refresh()},[]);
 const sync=async()=>{setBusy(true);try{const r=await invoke<any>('sync_now');setNotice(`Синхронизация: ${r.emails_synced} новых писем, ${r.posts_created} новых постов`);await refresh()}catch(e){setNotice(`Ошибка: ${e}`)}finally{setBusy(false)}};
 const publish=async(id:string)=>{setBusy(true);try{await invoke('publish_post',{postId:id});setNotice('Пост опубликован в Telegram');await refresh()}catch(e){setNotice(`Ошибка публикации: ${e}`)}finally{setBusy(false)}};
 return <div className="app"><aside className="sidebar"><div className="brand"><span className="logo">✉</span><span>Mail2Telegram</span></div><nav>{[['dashboard','⌂','Dashboard'],['emails','✉','Emails'],['posts','▤','Posts'],['automation','⚡','Automation'],['settings','⚙','Settings']].map(([id,icon,label])=><button key={id} className={page===id?'nav active':'nav'} onClick={()=>setPage(id)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebarBottom"><span className="dot"/> Monitoring</div></aside>
 <main className="main"><header><div><h1>{page==='dashboard'?'Dashboard':page[0].toUpperCase()+page.slice(1)}</h1><p className="muted">{status}</p></div><button className="primary small" onClick={sync} disabled={busy}>{busy?'Работаю…':'Синхронизировать'}</button></header>{notice&&<div className="notice">{notice}</div>}
 {page==='dashboard'&&<Dashboard posts={posts} config={config} publish={publish} sync={sync}/>} {page==='posts'&&<Posts posts={posts} publish={publish}/>} {page==='emails'&&<Emails emails={emails}/>} {page==='automation'&&<Automation onSaved={setNotice}/>} {page==='settings'&&<Settings config={config} onSaved={async()=>{await refresh();setNotice('Настройки сохранены')}}/>}
 </main></div>
}
function Dashboard({posts,config,publish,sync}:{posts:Post[];config:Config;publish:(id:string)=>void;sync:()=>void}){return <><section className="stats"><Stat n={String(posts.length)} t="Постов создано"/><Stat n={String(posts.filter(p=>p.status==='published').length)} t="Опубликовано"/><Stat n={String(posts.filter(p=>p.status==='draft').length)} t="На проверке"/><Stat n={config.gmail&&config.openai&&config.telegram?'OK':'!'} t="Конфигурация"/></section><section className="section"><div className="sectionTitle"><h2>Требуют проверки</h2><span className="badge">Approval mode</span></div>{posts.filter(p=>p.status==='draft').slice(0,5).map(p=><PostCard key={p.id} post={p} publish={publish}/>)}{posts.filter(p=>p.status==='draft').length===0&&<div className="empty"><h2>Черновиков нет</h2><p>Подключите сервисы и нажмите «Синхронизировать».</p></div>}</section><section className="section"><div className="sectionTitle"><h2>Подключения</h2></div><div className="connections"><Connection title="Gmail" ok={config.gmail} desc="OAuth-доступ к входящим письмам"/><Connection title="OpenAI" ok={config.openai} desc="Генерация заголовка и текста поста"/><Connection title="Telegram" ok={config.telegram} desc="Публикация в указанный канал"/></div></section></>}
function Posts({posts,publish}:{posts:Post[];publish:(id:string)=>void}){return <section className="section">{posts.map(p=><PostCard key={p.id} post={p} publish={publish}/>)}{!posts.length&&<div className="empty"><h2>Постов пока нет</h2></div>}</section>}
function PostCard({post,publish}:{post:Post;publish:(id:string)=>void}){return <article className="card post"><div className="postTop"><span className={'status '+post.status}>{post.status==='draft'?'Черновик':post.status==='published'?'Опубликован':'В очереди'}</span><span className="muted">{post.source||'Gmail'}</span></div><h3>{post.title||'Без заголовка'}</h3><p>{post.content}</p><div className="actions">{post.status==='draft'&&<button className="primary" onClick={()=>publish(post.id)}>Опубликовать в Telegram</button>}</div></article>}
function Stat({n,t}:{n:string;t:string}){return <div className="card stat"><strong>{n}</strong><span>{t}</span></div>}
function Connection({title,desc,ok}:{title:string;desc:string;ok:boolean}){return <div className="card connection"><div><h3>{title}</h3><p>{desc}</p></div><span className={ok?'connected':'notConnected'}>{ok?'Подключён':'Не подключён'}</span></div>}
function Emails({emails}:{emails:Email[]}){return <section className="section"><div className="card list">{emails.map(e=><div className="row" key={e.id}><div><b>{e.subject||'(без темы)'}</b><p>{e.sender||''}</p></div><span className="muted">{e.received_at||''}</span></div>)}{!emails.length&&<div className="empty"><h2>Писем пока нет</h2><p>Подключите Gmail и запустите синхронизацию.</p></div>}</div></section>}
function Automation({onSaved}:{onSaved:(s:string)=>void}){const [name,setName]=React.useState('Tech News → Telegram');const [sender,setSender]=React.useState('');const [subject,setSubject]=React.useState('');const [keywords,setKeywords]=React.useState('');const [mode,setMode]=React.useState('approval');const [prompt,setPrompt]=React.useState('');const save=async()=>{try{await invoke('save_automation',{input:{name,sender_filter:sender,subject_filter:subject,keywords,mode,prompt}});onSaved('Автоматизация сохранена')}catch(e){onSaved(String(e))}};return <section className="section"><div className="card form"><h2>Основная автоматизация</h2><label>Название<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Отправитель содержит<input value={sender} onChange={e=>setSender(e.target.value)} placeholder="news@example.com"/></label><label>Тема содержит<input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="AI"/></label><label>Ключевые слова<input value={keywords} onChange={e=>setKeywords(e.target.value)} placeholder="AI, OpenAI, startup"/></label><label>Режим<select value={mode} onChange={e=>setMode(e.target.value)}><option value="approval">Сначала показать мне</option><option value="automatic">Публиковать автоматически</option></select></label><label>Системная инструкция для AI<textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Например: пиши в стиле новостного канала…"/></label><button className="primary" onClick={save}>Сохранить</button></div></section>}
function Settings({config,onSaved}:{config:Config;onSaved:()=>void}){const [cid,setCid]=React.useState('');const [secret,setSecret]=React.useState('');const [openai,setOpenai]=React.useState('');const [token,setToken]=React.useState('');const [chat,setChat]=React.useState('');const save=async()=>{await invoke('save_credentials',{clientId:cid,clientSecret:secret,openaiApiKey:openai,telegramBotToken:token,telegramChatId:chat});onSaved()};const gmail=async()=>{try{const e=await invoke<string>('connect_gmail');alert(`Gmail подключён: ${e}`);onSaved()}catch(e){alert(String(e))}};const tg=async()=>{try{const x=await invoke<string>('test_telegram');alert(`Telegram: ${x}`);onSaved()}catch(e){alert(String(e))}};return <section className="section"><div className="card form"><h2>Подключения и ключи</h2><p className="muted">Секреты сохраняются в системном хранилище учётных данных, а не в SQLite.</p><label>Google OAuth Client ID<input value={cid} onChange={e=>setCid(e.target.value)} placeholder="...apps.googleusercontent.com"/></label><label>Google OAuth Client Secret<input type="password" value={secret} onChange={e=>setSecret(e.target.value)}/></label><div className="actions"><button className="secondary" onClick={save}>Сохранить ключи</button><button className="primary" onClick={gmail}>Подключить Gmail</button></div><hr/><label>OpenAI API key<input type="password" value={openai} onChange={e=>setOpenai(e.target.value)} placeholder="sk-…"/></label><label>Telegram Bot Token<input type="password" value={token} onChange={e=>setToken(e.target.value)} placeholder="123456:ABC…"/></label><label>Telegram Chat ID / @channel<input value={chat} onChange={e=>setChat(e.target.value)} placeholder="@my_channel или -100…"/></label><div className="actions"><button className="secondary" onClick={save}>Сохранить</button><button className="secondary" onClick={tg}>Проверить Telegram</button></div><div className="connectionGrid"><span>Gmail: {config.gmail?'✓':'—'}</span><span>OpenAI: {config.openai?'✓':'—'}</span><span>Telegram: {config.telegram?'✓':'—'}</span></div></div><div className="card form"><h2>Мониторинг</h2><label>Интервал<select onChange={async e=>{await invoke('save_settings',{intervalMinutes:Number(e.target.value),autostart:true,background:true});onSaved()}} defaultValue="5"><option value="1">1 минута</option><option value="5">5 минут</option><option value="15">15 минут</option><option value="30">30 минут</option></select></label><p className="muted">После запуска приложение само проверяет Gmail и обрабатывает новые письма.</p></div></section>}

createRoot(document.getElementById('root')!).render(<App/>);
